// Command cataloggen generates the negotiated Rudy extension catalogue from
// its normative contract table.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"os"
	"sort"
	"strings"
	"unicode"
)

type entry struct {
	capability   string
	method       string
	notification bool
}

func main() {
	contract := flag.String("contract", "", "path to rudy-contracts.md")
	output := flag.String("output", "", "generated Go output path")
	flag.Parse()
	if *contract == "" || *output == "" {
		fatalf("both -contract and -output are required")
	}

	b, err := os.ReadFile(*contract)
	if err != nil {
		fatalf("read contract: %v", err)
	}
	entries, err := parseTable(string(b))
	if err != nil {
		fatalf("parse contract: %v", err)
	}
	generated, err := render(entries)
	if err != nil {
		fatalf("render catalogue: %v", err)
	}
	if err := os.WriteFile(*output, generated, 0o644); err != nil {
		fatalf("write catalogue: %v", err)
	}
}

func parseTable(contract string) ([]entry, error) {
	const heading = "#### Rudy extension methods"
	start := strings.Index(contract, heading)
	if start < 0 {
		return nil, fmt.Errorf("missing %q heading", heading)
	}
	var entries []entry
	inTable := false
	seenCapabilities := make(map[string]bool)
	seenMethods := make(map[string]bool)
	for _, line := range strings.Split(contract[start+len(heading):], "\n") {
		if !strings.HasPrefix(line, "|") {
			if inTable {
				break
			}
			continue
		}
		columns := strings.Split(line, "|")
		if len(columns) < 6 {
			continue
		}
		capability := codeValue(strings.TrimSpace(columns[1]))
		if capability == "Capability" || strings.HasPrefix(capability, "---") {
			continue
		}
		methodColumn := strings.TrimSpace(columns[2])
		method := codeValue(methodColumn)
		if capability == "" || method == "" {
			return nil, fmt.Errorf("malformed extension row %q", line)
		}
		if seenCapabilities[capability] {
			return nil, fmt.Errorf("duplicate capability %q", capability)
		}
		if seenMethods[method] {
			return nil, fmt.Errorf("duplicate method %q", method)
		}
		seenCapabilities[capability] = true
		seenMethods[method] = true
		inTable = true
		entries = append(entries, entry{
			capability:   capability,
			method:       method,
			notification: strings.Contains(methodColumn, "notification"),
		})
	}
	if len(entries) == 0 {
		return nil, fmt.Errorf("extension table is empty")
	}
	sort.Slice(entries, func(i, j int) bool { return entries[i].capability < entries[j].capability })
	return entries, nil
}

func codeValue(column string) string {
	if !strings.HasPrefix(column, "`") {
		return column
	}
	end := strings.Index(column[1:], "`")
	if end < 0 {
		return ""
	}
	return column[1 : end+1]
}

func render(entries []entry) ([]byte, error) {
	var b bytes.Buffer
	b.WriteString("// Code generated by cataloggen; DO NOT EDIT.\n\n")
	b.WriteString("package acpext\n\n")
	b.WriteString("const (\n")
	for _, entry := range entries {
		fmt.Fprintf(&b, "\tCapability%s Capability = %q\n", identifier(entry.capability), entry.capability)
	}
	b.WriteString(")\n\n")
	b.WriteString("var capabilityNames = [...]string{\n")
	for _, entry := range entries {
		fmt.Fprintf(&b, "\tstring(Capability%s),\n", identifier(entry.capability))
	}
	b.WriteString("}\n\n")
	byMethod := append([]entry(nil), entries...)
	sort.Slice(byMethod, func(i, j int) bool { return byMethod[i].method < byMethod[j].method })
	b.WriteString("const (\n")
	for _, entry := range byMethod {
		fmt.Fprintf(&b, "\tMethod%s MethodName = %q\n", identifier(entry.capability), entry.method)
	}
	b.WriteString(")\n\n")
	b.WriteString("var methodNames = [...]string{\n")
	for _, entry := range byMethod {
		fmt.Fprintf(&b, "\tstring(Method%s),\n", identifier(entry.capability))
	}
	b.WriteString("}\n\n")
	b.WriteString("var catalogue = [...]Entry{\n")
	for _, entry := range entries {
		fmt.Fprintf(&b, "\t{Capability: string(Capability%s), Method: string(Method%s), Notification: %t},\n", identifier(entry.capability), identifier(entry.capability), entry.notification)
	}
	b.WriteString("}\n")
	return format.Source(b.Bytes())
}

func identifier(value string) string {
	var b strings.Builder
	upper := true
	for _, r := range value {
		if !unicode.IsLetter(r) && !unicode.IsDigit(r) {
			upper = true
			continue
		}
		if upper {
			r = unicode.ToUpper(r)
			upper = false
		}
		b.WriteRune(r)
	}
	return b.String()
}

func fatalf(format string, args ...any) {
	_, _ = fmt.Fprintf(os.Stderr, format+"\n", args...)
	os.Exit(1)
}
