// Code generated by cataloggen; DO NOT EDIT.

package acpext

const (
	CapabilityCommandList     Capability = "command.list"
	CapabilityCommandRun      Capability = "command.run"
	CapabilityRegistryList    Capability = "registry.list"
	CapabilityRegistryRefresh Capability = "registry.refresh"
	CapabilityServerShutdown  Capability = "server.shutdown"
	CapabilitySessionCompact  Capability = "session.compact"
	CapabilitySessionFork     Capability = "session.fork"
	CapabilitySessionShell    Capability = "session.shell"
	CapabilitySessionSteer    Capability = "session.steer"
	CapabilitySessionTitle    Capability = "session.title"
	CapabilitySessionUpdate   Capability = "session.update"
)

var capabilityNames = [...]string{
	string(CapabilityCommandList),
	string(CapabilityCommandRun),
	string(CapabilityRegistryList),
	string(CapabilityRegistryRefresh),
	string(CapabilityServerShutdown),
	string(CapabilitySessionCompact),
	string(CapabilitySessionFork),
	string(CapabilitySessionShell),
	string(CapabilitySessionSteer),
	string(CapabilitySessionTitle),
	string(CapabilitySessionUpdate),
}

const (
	MethodCommandList     MethodName = "_rudy/command/list"
	MethodCommandRun      MethodName = "_rudy/command/run"
	MethodRegistryList    MethodName = "_rudy/registry/list"
	MethodRegistryRefresh MethodName = "_rudy/registry/refresh"
	MethodServerShutdown  MethodName = "_rudy/server_shutdown"
	MethodSessionCompact  MethodName = "_rudy/session/compact"
	MethodSessionFork     MethodName = "_rudy/session/fork"
	MethodSessionTitle    MethodName = "_rudy/session/set_title"
	MethodSessionShell    MethodName = "_rudy/session/shell"
	MethodSessionSteer    MethodName = "_rudy/session/steer"
	MethodSessionUpdate   MethodName = "_rudy/session/update"
)

var methodNames = [...]string{
	string(MethodCommandList),
	string(MethodCommandRun),
	string(MethodRegistryList),
	string(MethodRegistryRefresh),
	string(MethodServerShutdown),
	string(MethodSessionCompact),
	string(MethodSessionFork),
	string(MethodSessionTitle),
	string(MethodSessionShell),
	string(MethodSessionSteer),
	string(MethodSessionUpdate),
}

var catalogue = [...]Entry{
	{Capability: string(CapabilityCommandList), Method: string(MethodCommandList), Notification: false, Side: "agent"},
	{Capability: string(CapabilityCommandRun), Method: string(MethodCommandRun), Notification: false, Side: "agent"},
	{Capability: string(CapabilityRegistryList), Method: string(MethodRegistryList), Notification: false, Side: "agent"},
	{Capability: string(CapabilityRegistryRefresh), Method: string(MethodRegistryRefresh), Notification: false, Side: "agent"},
	{Capability: string(CapabilityServerShutdown), Method: string(MethodServerShutdown), Notification: false, Side: "agent"},
	{Capability: string(CapabilitySessionCompact), Method: string(MethodSessionCompact), Notification: false, Side: "agent"},
	{Capability: string(CapabilitySessionFork), Method: string(MethodSessionFork), Notification: false, Side: "agent"},
	{Capability: string(CapabilitySessionShell), Method: string(MethodSessionShell), Notification: false, Side: "agent"},
	{Capability: string(CapabilitySessionSteer), Method: string(MethodSessionSteer), Notification: false, Side: "agent"},
	{Capability: string(CapabilitySessionTitle), Method: string(MethodSessionTitle), Notification: false, Side: "agent"},
	{Capability: string(CapabilitySessionUpdate), Method: string(MethodSessionUpdate), Notification: true, Side: "client"},
}
